### ISSUE TITLE
Store User Credentials in a local database

### ISSUE THREAD

**Issue by Dumnersm580** [gcbishal/BikeSparesInventorySystem#2]
I have a project similar to this and i was wondering what would be the best way of keeping user creds. (when restarting the app it keeps the users saved)

**Comment by Dumnersm580** [comment]
or were is the data stored

**Comment by bislerium** [comment]
Normally, for app specific data, prefer using app's isolated environment/directory which can be accessed using `Environment.SpecialFolder`. For credentials, you can store them using platform-specific secure storage mechanisms (e.g., Windows Credential Manager, macOS Keychain).
